-- AlterTable
ALTER TABLE `Article` MODIFY `publishedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `Comment` MODIFY `publishedDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
